### ISSUE TITLE
I always get Access denied  in ResourceController 

### ISSUE THREAD

**Issue by sofianehammami** [tuanngda/spring-boot-oauth2-demo#2]
Hi, 

STR :
1. Generate a token via Postman
2. Write http://localhost:9003/resources/admin in address bar
3. Use the generated token as a header or ur parameter 
4. Send the request using POST
5. Access denied.

**Comment by tuanngda** [comment]
Do you mind sharing which test case that you are trying to replicate in your browser? I am having no difficulty accessing the endpoint with the JWT token.

**Comment by sofianehammami** [comment]
My bad !! I was testing using a user not having required role.
